project:
  type: website

website:
  title: "Florida Census"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: analysis.qmd
        text: Income & Education
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



